### PR TITLE
Initial contribution 

### PR DESCRIPTION
**Pull request by cpotter302**
Initial commit contains:

- First version of the leda-app-deployer-vscode-extension
- Extension documentation
- Build resources
- Configuration files
- GitHub actions pipelines (need to be adjusted since the project is now rooted in a subdirectory of the repository)

In case of any questions please contact one of our [contributors](https://github.com/software-engineering-project-org/vscode-plugin-automotive-app-deployment/graphs/contributors)

### CODE REVIEW

**Comment by bs-jokri** [comment]
review request created at Eclipse Foundation: https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/11095

**Comment by eriksven** [comment]
In the meantime, the review request has been approved by the Eclipse Foundation IP Team ([see](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/11095))

**Comment by bs-jokri** [comment]
it seems husky cannot run anymore as the code is now in a sub directory

```
Ok to proceed? (y) 
husky-init updating package.json
  "husky install" command already exists in prepare script, skipping.
/Users/johannes/.npm/_npx/1ab9c0f68ac2536e/node_modules/husky/lib/index.js:23
        throw new Error(`.git can't be found (see ${url})`);
        ^
```

have you tried to build the plugin from this repository?

**Comment by bs-jokri** [comment]
I have moved to code one level up in the repository and was able to build according to your description in CONTRIBUTING.md. Could you check if there is a possibility to configure husky so that it is also possible to build the plugin from within the sub directory? Otherwise I haven't found anything, what hinders a merge of the PR

**Comment by cpotter302** [comment]
@bs-jokri the fix is pushed to the main branch, it should now be solved

**Comment by bs-jokri** [comment]
@cpotter302 great! I have checked and it works now as expected. Thanks for the fix!

**Comment by bs-jokri** [comment]
@mikehaller @vasilvas99 I checked the PR and it looks good to me. It could be merged from my side. Do you see any open issues before we can merge?

**Pull request merged**
